using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using UnityEngine;
using ArcCore.Serialization.NewtonsoftExtensions;

namespace ArcCore.Serialization
{
    [JsonHasPresets]
    public class DifficultyType
    {
        public string fullName;
        public string idName;

        public float sortOrder;

        public Color textColor;
        public Color baseColor;

        public bool Equals(DifficultyType other)
        {
            return fullName == other.fullName
                && idName == other.idName
                && sortOrder == other.sortOrder
                && textColor == other.textColor
                && baseColor == other.baseColor;
        }

        public override bool Equals(object obj)
            => obj is DifficultyType diffType && Equals(diffType);

        //Generated by VSCommunity
        public override int GetHashCode()
        {
            int hashCode = -817651219;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(fullName);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(idName);
            hashCode = hashCode * -1521134295 + sortOrder.GetHashCode();
            hashCode = hashCode * -1521134295 + textColor.GetHashCode();
            hashCode = hashCode * -1521134295 + baseColor.GetHashCode();
            return hashCode;
        }

        public static bool operator ==(DifficultyType a, DifficultyType b)
            => a.Equals(b);
        public static bool operator !=(DifficultyType a, DifficultyType b)
            => !(a == b);

        #region Standard Difficulty Classes
        [JsonPreset]
        public static DifficultyType Past => new DifficultyType
        {
            fullName = "Past",
            idName = "pst",

            sortOrder = 0f,

            textColor = ColorExtensions.FromHexcode("#FFFFFF"),
            baseColor = ColorExtensions.FromHexcode("#B0FFA0")
        };
        [JsonPreset]
        public static DifficultyType Present => new DifficultyType
        {
            fullName = "Present",
            idName = "prs",

            sortOrder = 1f,

            textColor = ColorExtensions.FromHexcode("#FFFFFF"),
            baseColor = ColorExtensions.FromHexcode("#0020FF")
        };
        [JsonPreset]
        public static DifficultyType Future => new DifficultyType
        {
            fullName = "Future",
            idName = "ftr",

            sortOrder = 1f,

            textColor = ColorExtensions.FromHexcode("#FFFFFF"),
            baseColor = ColorExtensions.FromHexcode("#FF2000")
        };
        [JsonPreset]
        public static DifficultyType Beyond = new DifficultyType
        {
            fullName = "Beyond",
            idName = "byd",

            sortOrder = 1f,

            textColor = ColorExtensions.FromHexcode("#FFFFFF"),
            baseColor = ColorExtensions.FromHexcode("#D00000")
        };
        #endregion
    }
}