using System;
using System.Collections.Generic;
using UnityEngine;

namespace ArcCore.Serialization
{
    public class DifficultyType : ICloneable, IEquatable<DifficultyType>
    {
        public string fullName;
        public string idName;

        public float sortOrder;

        public Color textColor;
        public Color baseColor;

        public object Clone() => new DifficultyType
        {
            fullName = fullName,
            idName = idName,
            sortOrder = sortOrder,
            textColor = textColor,
            baseColor = baseColor
        };

        public bool Equals(DifficultyType other)
        {
            return fullName == other.fullName
                && idName == other.idName
                && sortOrder == other.sortOrder
                && textColor == other.textColor
                && baseColor == other.baseColor;
        }

        public override bool Equals(object obj)
            => obj is DifficultyType diffType && Equals(diffType);

        //Generated by VSCommunity
        public override int GetHashCode()
        {
            int hashCode = -817651219;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(fullName);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(idName);
            hashCode = hashCode * -1521134295 + sortOrder.GetHashCode();
            hashCode = hashCode * -1521134295 + textColor.GetHashCode();
            hashCode = hashCode * -1521134295 + baseColor.GetHashCode();
            return hashCode;
        }

        public static bool operator ==(DifficultyType a, DifficultyType b)
            => a.Equals(b);
        public static bool operator !=(DifficultyType a, DifficultyType b)
            => !(a == b);

        #region Standard Difficulty Classes
        public static DifficultyType Past => new DifficultyType
        {
            fullName = "Past",
            idName = "pst",

            sortOrder = 0f,

            textColor = ColorExtensions.FromHexcode("#FFFFFF"),
            baseColor = ColorExtensions.FromHexcode("#B0FFA0")
        };
        public static DifficultyType Present => new DifficultyType
        {
            fullName = "Present",
            idName = "prs",

            sortOrder = 1f,

            textColor = ColorExtensions.FromHexcode("#FFFFFF"),
            baseColor = ColorExtensions.FromHexcode("#0020FF")
        };
        public static DifficultyType Future => new DifficultyType
        {
            fullName = "Future",
            idName = "ftr",

            sortOrder = 1f,

            textColor = ColorExtensions.FromHexcode("#FFFFFF"),
            baseColor = ColorExtensions.FromHexcode("#FF2000")
        };
        public static DifficultyType beyond = new DifficultyType
        {
            fullName = "Future",
            idName = "ftr",

            sortOrder = 1f,

            textColor = ColorExtensions.FromHexcode("#FFFFFF"),
            baseColor = ColorExtensions.FromHexcode("#D00000")
        };
        #endregion
        public static Dictionary<string, DifficultyType> Presets
            => new Dictionary<string, DifficultyType>
            {
            {"past", Past},
            {"present", Present},
            {"future", Future}
            };
    }
}